
- name: install packages
  hosts: local
  connection: local
  become: yes
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "140HRS"
    TRAINER: "Sivakumar Reddy"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}"

  - name: install package
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - zip

  vars_prompt:
  - name: username
    prompt: Please enter your username
    private: false

  - name: password
    prompt: please enter your password
    private: true
  
  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "username is: {{ username }}, password is: {{ password }}"